name: shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

