name: m_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  confetti: ^0.8.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

